#!/usr/bin/env python3
"""Writes lib/firebase_options.dart from the gitignored Firebase config files.

Run from mobile/:  python3 tool/gen_firebase_options.py

Reads android/app/google-services.json and ios/Runner/GoogleService-Info.plist
so Firebase.initializeApp(options: ...) works on both platforms without the
google-services Gradle plugin or an Xcode project edit. The output is
gitignored like its inputs.
"""
import json
import plistlib
import pathlib
import sys

root = pathlib.Path(__file__).resolve().parent.parent
gs = root / "android/app/google-services.json"
plist = root / "ios/Runner/GoogleService-Info.plist"
out = root / "lib/firebase_options.dart"

if not gs.exists() or not plist.exists():
    out.write_text("""// GENERATED by tool/gen_firebase_options.py without Firebase config files:
// the app builds, and pairs with fcmToken: null ("Push off").
import 'package:firebase_core/firebase_core.dart';

abstract final class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform =>
      throw UnsupportedError('No Firebase config; run tool/gen_firebase_options.py with the files in place');
}
""")
    print(f"no config files found; wrote a no-push placeholder to {out}", file=sys.stderr)
    sys.exit(0)

g = json.load(gs.open())
c = g["client"][0]
p = plistlib.load(plist.open("rb"))

android = dict(
    apiKey=c["api_key"][0]["current_key"],
    appId=c["client_info"]["mobilesdk_app_id"],
    messagingSenderId=g["project_info"]["project_number"],
    projectId=g["project_info"]["project_id"],
    storageBucket=g["project_info"].get("storage_bucket"),
)
ios = dict(
    apiKey=p["API_KEY"],
    appId=p["GOOGLE_APP_ID"],
    messagingSenderId=p["GCM_SENDER_ID"],
    projectId=p["PROJECT_ID"],
    storageBucket=p.get("STORAGE_BUCKET"),
    iosBundleId=p.get("BUNDLE_ID"),
)


def dart(opts):
    fields = ",\n".join(f"    {k}: '{v}'" for k, v in opts.items() if v)
    return f"FirebaseOptions(\n{fields},\n  )"


out.write_text(f"""// GENERATED by tool/gen_firebase_options.py — do not edit, do not commit.
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';

/// Firebase project `{g["project_info"]["project_id"]}`.
abstract final class DefaultFirebaseOptions {{
  static FirebaseOptions get currentPlatform {{
    if (Platform.isAndroid) return android;
    if (Platform.isIOS) return ios;
    throw UnsupportedError('No Firebase options for ${{Platform.operatingSystem}}');
  }}

  static const android = {dart(android)};

  static const ios = {dart(ios)};
}}
""")
print(f"wrote {out}")
