spring.application.name=auth
server.port=8001


####### DATASOURCE ######
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.url= jdbc:sqlite:db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
resend.apikey=${RESEND_API_KEY}
frontend.url=http://localhost:3000

spring.datasource.hikari.maximum-pool-size=1